openapi: 3.0.1
info:
  title: WeNet - Documentation
  description: This document is the starting point for accessing the various API documentation documents describing the components of the WeNet platform. You can get started by jumping to the documentation of your desired component!
    
    - [Incentive Server APIs](http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-incentive-server-api.json)
    
    - [Interaction Protocol Engine APIs](http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-interaction_protocol_engine-api.json)
    
    - [Personal Context Builder APIs](http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-personal_context_builder.json)
    
    - [Private Data Manager](http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-private_data_manager-api.json)
    
    - [Service REST APIs](http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-service-api.json)
    
    - [Social Learning APIs](http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-social-learning-api.json)
    
  contact:
    email: carlo.caprini@u-hopper.com
  version: 1.0.0
servers:
- url: /
paths:
  /object:
    post:
      summary: Nothing to do here
      responses:
        405:
          description: Invalid input
          content: {}
