openapi: 3.0.1
info:
  title: WeNet - Messages for the Applications
  description: This document collects the models describing the messages that the WeNet application is going to create and provide to application as responses for the users. In particular, there are going to be two type of messages

    * textual messages represent simple and general purpose messages used for notifying users about the conversation development (e.g. confirmations, errors, ...)

    * task notifications represent task dedicated messages providing information about the development of an ongoing task (e.g. there is a new volunteer for a task, there is a new task a user may be interested in, ...)


    Any application built on top of the WeNet platform will need to expose a dedicated endpoint where the messages for the application are going to be posted by WeNet.
    Such endpoint is going to be specified in the application configuration.

  version: 3.3.3

components:
  schemas:
    
    Message:
      type: object
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          description: The type of the message
          example: TaskVolunteerNotification
        attributes:
          type: object
          description: the attributes of the message, as key-value pairs.
          properties:
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true
          
    TextualMessage:
      description: A simple textual message from WeNet to the user
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum: 
          - TextualMessage
          description: The type of the message
          example: TextualMessage
        attributes:
          type: object
          properties:
            title:
              type: string
              description: The title of the message
            text:
              type: string
              description: The text of the message
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true

    TaskProposalNotification:
      description: This notification is used in order to propose a user to volunteer to a newly created task
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum:
          - TaskProposalNotification
          description: The type of the message
          example: TaskProposalNotification
        attributes:
          type: object
          description: the attributes of the message, as key-value pairs.
          properties:
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true

    TaskVolunteerNotification:
      description: This notification is used in order to notify the task creator that a new volunteer is proposing to participate to the task
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum:
          - TaskVolunteerNotification
          description: The type of the message
          example: TaskVolunteerNotification
        attributes:
          type: object
          properties:
            volunteerId:
              type: string
              description: The Wenet ID of the volunteer that is applying to the task
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true

    TaskSelectionNotification:
      description: This notification is used in order to notify the user who volunteered about the decision of the task creator
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum:
          - TaskSelectionNotification
          description: The type of the message
          example: TaskSelectionNotification
        attributes:
          type: object
          properties:
            outcome:
              type: string
              enum:
                - accepted
                - refused
              example: accepted
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true

    TaskConcludedNotification:
      description: This notification is used in order to notify task participants that a task has been completed, the outcome could be

        * completed (if completed correctly)

        * failed (if something went wrong)

        * cancelled (the creator cancelled the task)
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum:
          - TaskConcludedNotification
          description: The type of the message
          example: TaskConcludedNotification
        attributes:
          type: object
          properties:
            outcome:
              type: string
              description: The outcome of the task (has it been completed with success or not)
              enum:
                - cancelled
                - completed
                - failed
              example: completed
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              nullable: true
              example: 28961582-84d2-41d1-b555-c09dce046831
              
    IncentiveMessage:
      description: This message contains an incentive for an user
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum:
          - IncentiveMessage
          description: The type of the message
          example: IncentiveMessage
        attributes:
          type: object
          properties:
            issuer:
              type: string
              description: The issuer of the incentive
            content:
              type: string
              description: The content of the incentive
              example: we are happy to see your participation in the I-log app, you are doing a great job!
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true
              
    IncentiveBadge:
      description: This is a badge of an incentive
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        label:
          type: string
          enum:
          - IncentiveBadge
          description: The type of the message
          example: IncentiveBadge
        attributes:
          type: object
          properties:
            issuer:
              type: string
              description: The issuer of the incentive
            badgeClass:
              type: string
              description: the class of the badge
              example: hpqAdI7hQf2maQ13AW1jXA
            imageUrl:
              type: string
              description: the URL of the image of the badge
              example: https://wenet.server/media/uploads/badges/assertion-OYmfmtDFSIKG-qeZfXz4QQ.png
            criteria:
              type: string
              description: the criteria with which the badge was assigned
              example: The user will get this badge for 50 relations in Twitter
            message:
              type: string
              description: a human-readable text to be shown to the user when she receives the badge
              example: Congratulations! you just earned a new badge for your relations on Twitter
            communityId:
              type: string
              description: ID of the community related to the message
              nullable: true
            taskId:
              type: string
              description: The identifier of the target task
              example: 28961582-84d2-41d1-b555-c09dce046831
              nullable: true

    QuestionToAnswerMessage:
      title: Question to answer
      type: object
      properties:
        taskId:
          description: The id of the task associated with the question
          type: string
          nullable: false
        question:
          description: The question to answer to
          type: string
          nullable: false
        userId:
          description: The id of the user who proposed the question
          type: string
          nullable: false
        sensitive:
          description: Whether the question is sensitive or not, if it is sensitive the bot will let other people know to take extra care in answering the question
          type: boolean
          default: 'false'
          nullable: false
        anonymous:
          description: Whether to ask the question anonymously or not, if anonymous is chosen then the name of the user will not be shown
          type: boolean
          default: 'false'
          nullable: false
        positionOfAnswerer:
          description: How close the users should be to receive the question, if nearby is chosen the question has not the possibility to be postponed because the question requires a fast answer
          type: string
          nullable: false
          enum:
            - nearby
            - anywhere

    AnsweredQuestionMessage:
      title: Answer to question
      type: object
      properties:
        taskId:
          description: The id of the task associated with the question
          type: string
          nullable: false
        question:
          description: The question to answer to
          type: string
          nullable: false
        transactionId:
          description: The id of the transaction associated to the answer
          type: string
          nullable: false
        answer:
          description: The answer to the question
          type: string
          nullable: false
        userId:
          description: The id of the user who answered the question
          type: string
          nullable: false
        anonymous:
          description: Whether the user prefers to answer the question anonymously or not, if anonymous is chosen then the name of the user will not be shown
          type: boolean
          default: 'false'
          nullable: false

    AnsweredPickedMessage:
      title: Answer picked
      type: object
      properties:
        taskId:
          description: The id of the task associated with the question
          type: string
          nullable: false
        question:
          description: The question for which was picked the answer
          type: string
          nullable: false
        transactionId:
          description: The id of the transaction associated to the answer
          type: string
          nullable: false

    QuestionExpirationMessage:
      title: Question expiration
      type: object
      properties:
        taskId:
          description: The id of the task associated with the question
          type: string
          nullable: false
        question:
          description: The question for which was picked the answer
          type: string
          nullable: false
        listOfTransactionIds:
          description: The ids of the transactions associated to the answer
          type: array
          items:
            type: string
          nullable: false
