openapi: 3.0.1
info:
  title: WeNet - Authentication Manager
  description: This document describes the API exposed by the Authentication Manager of the WeNet platform. These the operations that can be performed by taking advantage of this component

    * Authenticate an user on the wenet platform using the OAUTH2 protocol

  contact:
    email: carlo.caprini@u-hopper.com
  version: 1.0.0

# servers:
# - url: /

paths:

  /api/oauth2/token:
    post:
      summary: Get a new token
      tags:
        - Module
      description: "This endpoint allows to get a new authorization token and refresh token. The access token must be use in the authenticated call in the authorization header. Example: 'authoerization: bearer jsdhfkjewhjsdnfakjh'"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/TokenRequest'
                - $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        200:
          description: Module created
          content:
            application/json:
              schema:
                type: object
                properties:
                  refresh_token:
                    type: string
                  token_type:
                    type: string
                    enum: [bearer]
                  access_token:
                    type: string
                  expires_in:
                    type: integer

  

components:
  schemas:
  
    TokenRequest:
      type: object
      description: The request you have to pwerform whe a user perform a login in order to get the acces token
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        grant_type:
          type: string
          enum: [authorization_code]
        redirect_uri:
          type: string
        code: 
          type: string
          description: The single use code received on the oauth callback
          
    RefreshTokenRequest:
      type: object
      description: The call you have to perform in order to renew an expired access token
      properties: 
        grant_type:
          type: string
          enum: [refresh_token]
        client_id:
          type: string
          enum: [client_id]
        client_secret:
          type: string
        refresh_token:
          type: string
          description: The refresh token you receive in the last token or refresh token request

    