openapi: 3.0.1
info:
  title: WeNet - Messages for the Applications
  description: This document collects the models describing the messages that the WeNet application is going to create and provide to application as responses for the users. In particular, there are going to be two type of messages

    * textual messages represent simple and general purpose messages used for notifying users about the conversation development (e.g. confirmations, errors, ...)

    * task notifications represent task dedicated messages providing information about the development of an ongoing task (e.g. there is a new volunteer for a task, there is a new task a user may be interested in, ...)


    Any application built on top of the WeNet platform will need to expose a dedicated endpoint where the messages for the application are going to be posted by WeNet.
    Such endpoint is going to be specified in the application configuration.

  contact:
    email: nicolo.pomini@u-hopper.com
  version: 2.0.0

components:
  schemas:
    
    Message:
      type: object
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          description: The type of the message
          example: TaskVolunteerNotification
        attributes:
          type: object
          description: the attributes of the message, as key-value pairs.

    NewUserForPlatform:
      description: A new user activated an app platform
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum: 
          - NewUserForPlatform
          description: The type of the message
          example: NewUserForPlatform
        attributes:
          type: object
          description: the attributes of the message, as key-value pairs.
          properties:
            platform:
              type: string
              enum:
              - Telegram
              description: The social platform of the wenet application
              
    TextualMessage:
      description: A simple textual message from WeNet to the user
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum: 
          - TextualMessage
          description: The type of the message
          example: TextualMessage
        attributes:
          type: object
          properties:
            title:
              type: string
              description: The title of the message
            text:
              type: string
              description: The text of the message

    TaskNotification:
      description: A message regarding a task, it could be about

        * a task proposal to a possible volunteer

        * a volunteer proposal to the task creator

        * a message about an activa task exchanged between two task participants

        * the conclusion of a task
      allOf:
        - $ref: '#/components/schemas/Message'
      properties:
        type:
          example: taskNotification
          description: The task notification type
          enum:
            - taskNotification
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        # task:
        notificationType:
          type: string
          enum:
            - taskProposal
            - taskVolunteer
            - messageFromUser
            - taskConcluded
          example: taskProposal

    TaskProposalNotification:
      description: This notification is used in order to propose a user to volunteer to a newly created task
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum:
          - TaskProposalNotification
          description: The type of the message
          example: TaskProposalNotification

    TaskVolunteerNotification:
      description: This notification is used in order to notify the task creator that a new volunteer is proposing to participate to the task
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum:
          - TaskVolunteerNotification
          description: The type of the message
          example: TaskVolunteerNotification
        attributes:
          type: object
          properties:
            volunteerId:
              type: string
              description: The Wenet ID of the volunteer that is applying to the task

    TaskSelectionNotification:
      description: This notification is used in order to notify the user who volunteered about the decision of the task creator
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum:
          - TaskSelectionNotification
          description: The type of the message
          example: TaskSelectionNotification
        attributes:
          type: object
          properties:
            outcome:
              type: string
              enum:
                - accepted
                - refused
              example: accepted

    MessageFromUserNotification:
      description: This notification is used in order to send a message exchanged between two participants to the same task
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum:
          - MessageFromUserNotification
          description: The type of the message
          example: MessageFromUserNotification
        attributes:
          type: object
          properties:
            senderId:
              type: string
              description: The wenet ID of the user who wrote the message for the recipient user
              example: ef3990b4-d75e-4339-b78a-125c23ab4614
            title:
              example: Message from Paperino
            text:
              description: The text written by the sender user
              example: Cool, loking forward to participate to your task!

    TaskConcludedNotification:
      description: This notification is used in order to notify task participants that a task has been completed, the outcome could be

        * completed (if completed correctly)

        * failed (if something went wrong)

        * cancelled (the creator cancelled the task)
      properties:
        appId:
          type: string
          description: ID of the Wenet application related to the message
          example: 822jhluNZP
        communityId:
          type: string
          description: ID of the community related to the message
        taskId:
          type: string
          description: The identifier of the target task
          example: 28961582-84d2-41d1-b555-c09dce046831
        receiverId:
          type: string
          description: The Wenet user ID of the recipient of the message
          example: a6822c47-f1b8-4c21-80bd-1d025266c3c7
        contentType:
          type: string
          example: task
        label:
          type: string
          enum:
          - TaskConcludedNotification
          description: The type of the message
          example: TaskConcludedNotification
        attributes:
          type: object
          properties:
            outcome:
              type: string
              description: The outcome of the task (has it been completed with success or not)
              enum:
                - cancelled
                - completed
                - failed
              example: completed
